# Generated by Django 5.2.4 on 2025-07-13 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha'),
        ),
    ]
